### ISSUE TITLE
Cannot read property 'jquery' of null

### ISSUE THREAD

**Issue by Successful** [Successful/ngFutureProof#1]
System js is throwing:

```
Uncaught (in promise) Error: Cannot read property 'jquery' of null
	Error loading http://localhost:3000/src/index.js
    at Object.window.angular.bootstrap (chrome-extension://aadgmnobpdmgmigaicncghmmoeflnamj/ng-inspector.js:1509:12)
    at Object.bootstrap (http://localhost:3000/vendor/jspm_packages/npm/ng-forward@0.0.1-alpha.12/cjs/bootstrap.js:16:18)
    at execute (http://localhost:3000/src/index.js:16:26)
    at u (http://localhost:3000/vendor/jspm_packages/system.js:5:3446)
    at Object.execute (http://localhost:3000/vendor/jspm_packages/system.js:5:6334)
    at b (http://localhost:3000/vendor/jspm_packages/system.js:4:10328)
    at x (http://localhost:3000/vendor/jspm_packages/system.js:4:10707)
    at p (http://localhost:3000/vendor/jspm_packages/system.js:4:8585)
    at h (http://localhost:3000/vendor/jspm_packages/system.js:4:8970)
    at http://localhost:3000/vendor/jspm_packages/system.js:4:7239
```

**Comment by Successful** [comment]
The issue was not related to the code, used a plugin called ng-inspector that caused the error.
